package cn.adsit.iva.preroll.pojo;

import cn.adsit.iva.common.pojo.Pojo;

/**
 * ValueAdd generated by MyEclipse Persistence Tools
 */

public class ValueAdd extends Pojo
{
	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -198393734181405693L;

	/**
	 * 增值类型：鲜花投票类型
	 */
	public static final int VALUE_ADD_TYPE_FLOWER = 1;

	/**
	 * 增值类型：砖头投票类型
	 */
	public static final int VALUE_ADD_TYPE_TILE = 2;

	/**
	 * 增值类型：下载类型
	 */
	public static final int VALUE_ADD_TYPE_DOWNLOAD = 4;

	/**
	 * 增值类型：视频分享类型
	 */
	public static final int VALUE_ADD_TYPE_SHARE = 8;

	/**
	 * 动作状态：正常
	 */
	public static final int ACTION_STATE_NORMAL = 1;

	/**
	 * 动作状态：恶意
	 */
	public static final int ACTION_STATE_SPITE = 2;

	/**
	 * 动作状态：系统
	 */
	public static final int ACTION_STATE_SYSTEM = 4;

	// Fields

	private String valueAddId;
	private String videoDemandId;
	private String publishVideoId;
	private String workstationId;
	private String workstationPageId;
	private String pageUrl;
	private String advertiserId;
	private String videoId;
	private Integer duration;
	private Integer playLength;
	private String userIp;
	private String userId;
	private String zoneName;
	private String vaTime;
	private String vaDate;
	private String vaYearWeek;
	private String vaYearSeason;
	private String vaYear;
	private Integer vaType;
	private String actionImplNumber;
	private Integer actionState;

	// Constructors

	public ValueAdd()
	{
	}

	// Property accessors

	public String getValueAddId()
	{
		return this.valueAddId;
	}

	public void setValueAddId(String valueAddId)
	{
		this.valueAddId = valueAddId;
	}

	public String getVideoDemandId()
	{
		return this.videoDemandId;
	}

	public void setVideoDemandId(String videoDemandId)
	{
		this.videoDemandId = videoDemandId;
	}

	public String getPublishVideoId()
	{
		return this.publishVideoId;
	}

	public void setPublishVideoId(String publishVideoId)
	{
		this.publishVideoId = publishVideoId;
	}

	public String getWorkstationId()
	{
		return this.workstationId;
	}

	public void setWorkstationId(String workstationId)
	{
		this.workstationId = workstationId;
	}

	public String getWorkstationPageId()
	{
		return this.workstationPageId;
	}

	public void setWorkstationPageId(String workstationPageId)
	{
		this.workstationPageId = workstationPageId;
	}

	public String getPageUrl()
	{
		return this.pageUrl;
	}

	public void setPageUrl(String pageUrl)
	{
		this.pageUrl = pageUrl;
	}

	public String getAdvertiserId()
	{
		return this.advertiserId;
	}

	public void setAdvertiserId(String advertiserId)
	{
		this.advertiserId = advertiserId;
	}

	public String getVideoId()
	{
		return this.videoId;
	}

	public void setVideoId(String videoId)
	{
		this.videoId = videoId;
	}

	public Integer getDuration()
	{
		return this.duration;
	}

	public void setDuration(Integer duration)
	{
		this.duration = duration;
	}

	public Integer getPlayLength()
	{
		return this.playLength;
	}

	public void setPlayLength(Integer playLength)
	{
		this.playLength = playLength;
	}

	public String getUserIp()
	{
		return this.userIp;
	}

	public void setUserIp(String userIp)
	{
		this.userIp = userIp;
	}

	public String getZoneName()
	{
		return this.zoneName;
	}

	public void setZoneName(String zoneName)
	{
		this.zoneName = zoneName;
	}

	public String getVaTime()
	{
		return this.vaTime;
	}

	public void setVaTime(String vaTime)
	{
		this.vaTime = vaTime;
	}

	public String getVaDate()
	{
		return this.vaDate;
	}

	public void setVaDate(String vaDate)
	{
		this.vaDate = vaDate;
	}

	public String getVaYearWeek()
	{
		return this.vaYearWeek;
	}

	public void setVaYearWeek(String vaYearWeek)
	{
		this.vaYearWeek = vaYearWeek;
	}

	public String getVaYearSeason()
	{
		return this.vaYearSeason;
	}

	public void setVaYearSeason(String vaYearSeason)
	{
		this.vaYearSeason = vaYearSeason;
	}

	public String getVaYear()
	{
		return this.vaYear;
	}

	public void setVaYear(String vaYear)
	{
		this.vaYear = vaYear;
	}

	public Integer getVaType()
	{
		return this.vaType;
	}

	public void setVaType(Integer vaType)
	{
		this.vaType = vaType;
	}

	public String getActionImplNumber()
	{
		return actionImplNumber;
	}

	public void setActionImplNumber(String actionImplNumber)
	{
		this.actionImplNumber = actionImplNumber;
	}

	public Integer getActionState()
	{
		return actionState;
	}

	public void setActionState(Integer actionState)
	{
		this.actionState = actionState;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
}