package file.pojo;

import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.Date;

import cn.adsit.common.util.DateUtil;
import cn.adsit.iva.common.pojo.LifePojo;

/**
 * VideoDemand generated by MyEclipse - Hibernate Tools
 */

public class VideoDemand extends LifePojo
{
	/**
	 * SerialID
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 汇总状态:等待汇总
	 */
	public static final int GATHER_STATE_WAIT = 1;

	/**
	 * 汇总状态:汇总成功
	 */
	public static final int GATHER_STATE_SUCCESS = 2;

	/**
	 * 汇总状态:汇总失败
	 */
	public static final int GATHER_STATE_FAIL = 4;

	// Fields

	private String videoDemandId;
	private String workstationId;// 工作站ID
	private String workstationPageId;
	private String userIp;
	private String videoDemandTime;
	private String videoDemandYear;
	private String videoDemandMonth;
	private String videoDemandWeek;
	private String videoDemandDay;
	private Integer gatherState;
	private Integer processCount;

	// Constructors

	public VideoDemand()
	{
		Date curDate = new Date();
		this.videoDemandTime = DateUtil.getCurrTime();
		this.videoDemandYear = DateUtil.getYear(curDate);
		this.videoDemandMonth = DateUtil.getYearMonth(curDate);
		this.videoDemandWeek = DateUtil.getYearWeek(curDate);
		this.videoDemandDay = DateUtil.getCurrDate();
		this.gatherState = VideoDemand.GATHER_STATE_WAIT;
	}

	// Property accessors

	public String getVideoDemandId()
	{
		return this.videoDemandId;
	}

	public void setVideoDemandId(String videoDemandId)
	{
		this.videoDemandId = videoDemandId;
	}

	public String getWorkstationId()
	{
		return workstationId;
	}

	public void setWorkstationId(String workstationId)
	{
		this.workstationId = workstationId;
	}

	public String getWorkstationPageId()
	{
		return this.workstationPageId;
	}

	public void setWorkstationPageId(String workstationPageId)
	{
		this.workstationPageId = workstationPageId;
	}

	public String getUserIp()
	{
		return this.userIp;
	}

	public void setUserIp(String userIp)
	{
		this.userIp = userIp;
	}

	public String getVideoDemandTime()
	{
		return this.videoDemandTime;
	}

	public void setVideoDemandTime(String videoDemandTime)
	{
		this.videoDemandTime = videoDemandTime;
	}

	public String getVideoDemandYear()
	{
		return this.videoDemandYear;
	}

	public void setVideoDemandYear(String videoDemandYear)
	{
		this.videoDemandYear = videoDemandYear;
	}

	public String getVideoDemandMonth()
	{
		return this.videoDemandMonth;
	}

	public void setVideoDemandMonth(String videoDemandMonth)
	{
		this.videoDemandMonth = videoDemandMonth;
	}

	public String getVideoDemandWeek()
	{
		return this.videoDemandWeek;
	}

	public void setVideoDemandWeek(String videoDemandWeek)
	{
		this.videoDemandWeek = videoDemandWeek;
	}

	public String getVideoDemandDay()
	{
		return this.videoDemandDay;
	}

	public void setVideoDemandDay(String videoDemandDay)
	{
		this.videoDemandDay = videoDemandDay;
	}

	public Integer getGatherState()
	{
		return this.gatherState;
	}

	public void setGatherState(Integer gatherState)
	{
		this.gatherState = gatherState;
	}

	public Integer getProcessCount()
	{
		return processCount;
	}

	public void setProcessCount(Integer processCount)
	{
		this.processCount = processCount;
	}

	/**
	 * 对象序列化为XML字符串
	 * 
	 * @return XML字符串
	 */
	public String toSerialXml() throws Exception
	{

		StringBuffer serialXml = new StringBuffer();
		serialXml.append("<cn.adsit.iva.preroll.pojo.VideoDemand>");
		serialXml.append("<videoDemandId>" + (this.videoDemandId == null ? "" : URLEncoder.encode(this.videoDemandId, "GBK")) + "</videoDemandId>");
		serialXml.append("<workstationId>" + (this.workstationId == null ? "" : URLEncoder.encode(this.workstationId, "GBK")) + "</workstationId>");
		serialXml.append("<workstationPageId>" + (this.workstationPageId == null ? "" : URLEncoder.encode(this.workstationPageId, "GBK"))
				+ "</workstationPageId>");
		serialXml.append("<userIp>" + (this.userIp == null ? "" : URLEncoder.encode(this.userIp, "GBK")) + "</userIp>");
		serialXml.append("<videoDemandTime>" + (this.videoDemandTime == null ? "" : URLEncoder.encode(this.videoDemandTime, "GBK")) + "</videoDemandTime>");
		serialXml.append("<videoDemandYear>" + (this.videoDemandYear == null ? "" : URLEncoder.encode(this.videoDemandYear, "GBK")) + "</videoDemandYear>");
		serialXml.append("<videoDemandMonth>" + (this.videoDemandMonth == null ? "" : URLEncoder.encode(this.videoDemandMonth, "GBK")) + "</videoDemandMonth>");
		serialXml.append("<videoDemandWeek>" + (this.videoDemandWeek == null ? "" : URLEncoder.encode(this.videoDemandWeek, "GBK")) + "</videoDemandWeek>");
		serialXml.append("<videoDemandDay>" + (this.videoDemandDay == null ? "" : URLEncoder.encode(this.videoDemandDay, "GBK")) + "</videoDemandDay>");
		serialXml.append("<gatherState>" + (this.gatherState == null ? "" : this.gatherState) + "</gatherState>");
		serialXml.append("<processCount>" + (this.processCount == null ? "" : this.processCount) + "</processCount>");

		// 父类LifePojo内部属性序列
		super.innerSerialXml(serialXml);
		// 返回
		serialXml.append("</cn.adsit.iva.preroll.pojo.VideoDemand>");
		return serialXml.toString();

	}

	/**
	 * 从序列化XML字符串还原对象
	 * 
	 * @param serialXml XML字符串
	 */
	public void fromSerialXml(String serialXml) throws Exception
	{
		String node = null;
		if (serialXml.indexOf("<videoDemandId>") != -1 && serialXml.indexOf("</videoDemandId>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<videoDemandId>") + 15, serialXml.indexOf("</videoDemandId>"));
			if (node.length() != 0)
				this.videoDemandId = URLDecoder.decode(node, "GBK");
		}
		if (serialXml.indexOf("<workstationId>") != -1 && serialXml.indexOf("</workstationId>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<workstationId>") + 15, serialXml.indexOf("</workstationId>"));
			if (node.length() != 0)
				this.workstationId = URLDecoder.decode(node, "GBK");
		}
		if (serialXml.indexOf("<workstationPageId>") != -1 && serialXml.indexOf("</workstationPageId>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<workstationPageId>") + 19, serialXml.indexOf("</workstationPageId>"));
			if (node.length() != 0)
				this.workstationPageId = URLDecoder.decode(node, "GBK");
		}
		if (serialXml.indexOf("<userIp>") != -1 && serialXml.indexOf("</userIp>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<userIp>") + 8, serialXml.indexOf("</userIp>"));
			if (node.length() != 0)
				this.userIp = URLDecoder.decode(node, "GBK");
		}
		if (serialXml.indexOf("<videoDemandTime>") != -1 && serialXml.indexOf("</videoDemandTime>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<videoDemandTime>") + 17, serialXml.indexOf("</videoDemandTime>"));
			if (node.length() != 0)
				this.videoDemandTime = URLDecoder.decode(node, "GBK");
		}
		if (serialXml.indexOf("<videoDemandYear>") != -1 && serialXml.indexOf("</videoDemandYear>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<videoDemandYear>") + 17, serialXml.indexOf("</videoDemandYear>"));
			if (node.length() != 0)
				this.videoDemandYear = URLDecoder.decode(node, "GBK");
		}
		if (serialXml.indexOf("<videoDemandMonth>") != -1 && serialXml.indexOf("</videoDemandMonth>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<videoDemandMonth>") + 18, serialXml.indexOf("</videoDemandMonth>"));
			if (node.length() != 0)
				this.videoDemandMonth = URLDecoder.decode(node, "GBK");
		}
		if (serialXml.indexOf("<videoDemandWeek>") != -1 && serialXml.indexOf("</videoDemandWeek>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<videoDemandWeek>") + 17, serialXml.indexOf("</videoDemandWeek>"));
			if (node.length() != 0)
				this.videoDemandWeek = URLDecoder.decode(node, "GBK");
		}
		if (serialXml.indexOf("<videoDemandDay>") != -1 && serialXml.indexOf("</videoDemandDay>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<videoDemandDay>") + 16, serialXml.indexOf("</videoDemandDay>"));
			if (node.length() != 0)
				this.videoDemandDay = URLDecoder.decode(node, "GBK");
		}
		if (serialXml.indexOf("<gatherState>") != -1 && serialXml.indexOf("</gatherState>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<gatherState>") + 13, serialXml.indexOf("</gatherState>"));
			if (node.length() != 0)
				this.gatherState = Integer.valueOf(node);
		}
		if (serialXml.indexOf("<processCount>") != -1 && serialXml.indexOf("</processCount>") != -1)
		{
			node = serialXml.substring(serialXml.indexOf("<processCount>") + 14, serialXml.indexOf("</processCount>"));
			if (node.length() != 0)
				this.processCount = Integer.valueOf(node);
		}
		// 父类LifePojo还原
		super.fromSerialXml(serialXml);
	}
}